name: Update WAQI Data

on:
  schedule:
    - cron: '0 * * * *'  # This runs every hour
  workflow_dispatch:   # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp nest_asyncio pymongo requests

      - name: Run update script
        env:
          WAQI_API_KEY: ${{ secrets.WAQI_API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          DATABASE_NAME: "aqidb"
          COLLECTION_NAME: "waqi_stations"
        run: python app.py
